### PR TITLE
feat: support completing-read

### PR DESCRIPTION
**Pull request by bard**
To try: `M-x customize-variable RET run-command-completion-method RET` and choose "completing-read".

Fixes: #2

### CODE REVIEW

**Comment by clemera** [comment]
Thank you! Seems to work fine :+1:

**Comment by clemera** [comment]
Personally I would default to `completing-read`, ivy and helm will be automatically used when their mode is enabled. Though if you use specific feature of them I would check for the mode instead of using `featurep`. For example I have helm and ivy installed but usually prefer to use default completion with Selectrum.

**Comment by bard** [comment]
> Personally I would default to completing-read, this way ivy and helm will be
> automatically used when their mode is enabled. Though if you use specific
> feature of them I would check for the mode instead of using featurep. For
> example I have helm and ivy installed but usually prefer to use default
> completion with Selectrum.

I just did the former, but the latter seems like an even better idea,
I'll do that instead.

**Comment by bard** [comment]
@clemera merged. Thanks for reporting and for taking the time to test.

**Pull request merged**
