### PR TITLE
Make run-command-run-method configurable per command

### PR DESCRIPTION
**Pull request by jdormit**
This is an awesome package! I've found it useful to be able to have some of my commands run in compilation mode and others in term, so this adds a command list property to set that.

### CODE REVIEW

**Comment by bard** [comment]
Thanks @jdormit, that's a record time contribution! My intention was to eventually phase out the compilation method, since the terminal method does everything the former was doing, plus wherever possible I try to keep things aligned with my workflow so I can notice when I introduce bugs. Did you find scenarios where the compilation mode provides something compelling over term-mode+compilation-minor-mode?

**Comment by jdormit** [comment]
Nothing particularly compelling, just personal preference - I think it can be nice sometimes to have a command that explicitly can't accept user input. It's not a particularly strong preference, to be honest. Feel free to close this out if the intention is to do away with the compilation method entirely, I can see why it's appealing to have all commands use the same workflow.

**Comment by jdormit** [comment]
Ok, I've played a bit more with the terminal method, and it seems totally workable for me. I'm going to set `run-command-run-method` to `'term` and close this out.

**Comment by bard** [comment]
Ah, I see where you're coming from. Running with the `term` method should also prevent user input (courtesy of `compilation-minor-mode`, I believe), if you can enter input despite that please let me know, it would be a bug.

**Pull request closed without merging**
